---
title: "Data Wrangling"
author: "All of us"
date: "10/30/2019"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: inline
---
## R Markdown

#Obtain Alaskan Data
```{r}
library(tidyverse)
library(dataRetrieval)


AlaskaSites_RAW <- whatNWISsites(stateCd="02", parameterCd = "00060")
```


```{r}
## Filter Alaska sites for streams
AlaskaSites_Stream <- AlaskaSites_RAW %>%
  filter(site_tp_cd=="ST")

## Latitude bin size in degrees
Lat_Step <- (max(AlaskaSites_Stream$dec_lat_va) - 
               min(AlaskaSites_Stream$dec_lat_va))/10

## Create a new column with latitude bin
AlaskaSites_Stream <- AlaskaSites_Stream %>%
  mutate(Latitude_Bin = floor(((dec_lat_va - min(dec_lat_va))/Lat_Step)+1))

## Write site list to csv

write.csv(AlaskaSites_Stream, "../DATA/PROCESSED/Alaska_Streamflow_Sites.csv")

## Bin Assignments
## Gaby = 5
## Tristen = 6 & 7
## Yixin = 1-3
## Walker = 8-11 & 4

## Filter code
Alaska_Gaby <- filter(AlaskaSites_Stream, Latitude_Bin == 5)
```


```{r}

#Discharge data for all sites
discharge.dat <- readNWISdv(siteNumbers = c("15297680","15297610", "15072000", "15052500",
                                      "15276000", "15304000", "15514000", "15453500",
                                      "15908000", "15896000"), #Bins 1-10
                     parameterCd = c("00060"), # Discharge
                     startDate = "",
                     endDate = "")

#Site data for all sites
site.dat <- readNWISsite(siteNumbers = c("15297680","15297610", "15072000", "15052500",
                                      "15276000", "15304000", "15514000", "15453500",
                                      "15908000", "15896000"))

#Write raw files
#write.csv(discharge.dat, row.names = FALSE,  file = "../DATA/RAW/NWIS_Discharge.csv")
#write.csv(site.dat, row.names = FALSE,  file = "../DATA/RAW/NWIS_SiteInfo.csv")

```

``` {r} 
#Add bin numbers 6 and 7 to raw data
getwd()
bins_6_7 <- read.csv("../DATA/RAW/NOAA_Precip_Bin6_7.csv")
bins_6_7 <- bins_6_7 %>% mutate(Bin = STATION)

bins_6_7$Bin <- 
  ifelse(bins_6_7$Bin == "USW00026615", "6", 
         "7")

#Write as processed csv
#write.csv(bins_6_7, row.names = FALSE,  file = "../DATA/PROCESSED/NOAA_Temp_Precip_Bin_6_7.csv")

```
