---
title: "Discharge_Analysis"
author: "Yixin Wen"
date: "11/11/2019"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r, setup, include=FALSE}
getwd()

library(tidyverse)
library(lubridate)
library(dataRetrieval)
library(trend)
library(forecast)
library(tseries)
library(zoo)
theme_set(theme_classic())
```


```{r,echo = FALSE}
# import data
AlaskaTempPrecipDischarge <- read_csv("./DATA/PROCESSED/AlaskaTempPrecipDischarge.csv")
# transform bin into factor
AlaskaTempPrecipDischarge$Bin <- as.factor(AlaskaTempPrecipDischarge$Bin)

AlaskaTempPrecipDischarge$DATE <- as.Date(AlaskaTempPrecipDischarge$DATE,
                                          format = "%Y-%m-%d")
#Extract date and discharge data
AlaskaDischarge <- AlaskaTempPrecipDischarge%>%
  select("DATE", "Bin","STATION","NAME", "site_no", "Discharge")
#drop na
AlaskaDischarge<-AlaskaDischarge%>%drop_na()

# plot discharge  over time for 10 latitude bins
discharge_plot <- ggplot(AlaskaDischarge,aes(x = DATE, y = Discharge))+
  geom_line()+ # add a representative line
  facet_wrap(~Bin, nrow = 3, ncol = 3)+
  labs(x = "Date", y =expression("Discharge (ft"^3*"/s)"))
print(discharge_plot)
  
```

for bin 2, choose dataset from time 1995, for bin 3 choose dataset from 1948, for bin 4, use linear interplotation to fill the missing data from 1994-10 to 1996-10
```{r}
# bin 2: choose >1995
# bin 3: choose>1949
# bin 4: missing 1994-10 to 1996-10 

#Bin 1
AlaskaDischarge_1.Monthly <- AlaskaDischarge %>%
  filter(Bin ==1)%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year>=1968 & Year <= 1973)

 
#Bin 2
AlaskaDischarge_2.Monthly <- AlaskaDischarge %>%
  filter(Bin == 2)%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >= 1996 & Year <= 2018)


#Bin 3
AlaskaDischarge_3.Monthly <- AlaskaDischarge %>%
  filter(Bin == 3 )%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >=1989 & Year <= 2018)
  

#Bin 4
AlaskaDischarge_4_ori.Monthly <- AlaskaDischarge %>%
  filter(Bin == 4 )%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >=1966 & Year <= 2018)

AlaskaDischarge_4_mean <- AlaskaDischarge_4_ori.Monthly%>%
  group_by(Month)%>%
  summarise(Discharge = mean(Discharge))

AlaskaDischarge_4_1994 <- data.frame(Year = 1994, Month =c(10,11,12) , Discharge = AlaskaDischarge_4_mean$Discharge[10:12])
AlaskaDischarge_4_1995 <- data.frame(Year = 1995, Month =c(1,2,3,4,5,6,7,8,9,10,11,12) , Discharge = AlaskaDischarge_4_mean$Discharge[1:12])
AlaskaDischarge_4_1996 <- data.frame(Year = 1996, Month =c(1,2,3,4,5,6,7,8,9) , Discharge = AlaskaDischarge_4_mean$Discharge[1:9])

AlaskaDischarge_4_add <- rbind(AlaskaDischarge_4_1994, AlaskaDischarge_4_1995, AlaskaDischarge_4_1996)

AlaskaDischarge_4.Monthly <-rbind(data.frame(AlaskaDischarge_4_ori.Monthly), data.frame(AlaskaDischarge_4_add))


# Bin 5 
AlaskaDischarge_5.Monthly <- AlaskaDischarge %>%
  filter(Bin ==5)%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >= 1954 & Year <= 2018)
  

# Bin 6 
AlaskaDischarge_6_ori.Monthly <- AlaskaDischarge %>%
  filter(Bin ==6)%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >= 1952 & Year <= 2018)

AlaskaDischarge_6_mean <- AlaskaDischarge_6_ori.Monthly%>%
  group_by(Month)%>%
  summarise(Discharge = mean(Discharge))

AlaskaDischarge_6_1994 <- data.frame(Year = 1994, Month =c(10,11,12) , Discharge = AlaskaDischarge_6_mean$Discharge[10:12])
AlaskaDischarge_6_1995 <- data.frame(Year = 1995, Month =c(1,2,3,4,5,6,7,8,9) , Discharge = AlaskaDischarge_6_mean$Discharge[1:9])

AlaskaDischarge_6_add <- rbind(AlaskaDischarge_6_1994, AlaskaDischarge_6_1995)

AlaskaDischarge_6.Monthly <-rbind(data.frame(AlaskaDischarge_6_ori.Monthly), data.frame(AlaskaDischarge_6_add))
  

#Bin 7
AlaskaDischarge_7_ori.Monthly <- AlaskaDischarge %>%
  filter(Bin ==7)%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >= 1950 & Year <= 2018)

AlaskaDischarge_7_mean <- AlaskaDischarge_7_ori.Monthly%>%
  group_by(Month)%>%
  summarise(Discharge = mean(Discharge))

AlaskaDischarge_7_1966 <- data.frame(Year = 1966, Month =7 , Discharge = AlaskaDischarge_7_mean$Discharge[7])
AlaskaDischarge_7_2006 <- data.frame(Year = 2006, Month =c(7,8,9) , Discharge = AlaskaDischarge_7_mean$Discharge[7:9])
AlaskaDischarge_7_2007 <- data.frame(Year = 2007, Month =12 , Discharge = AlaskaDischarge_7_mean$Discharge[12])
AlaskaDischarge_7_2008 <- data.frame(Year = 2008, Month =6 , Discharge = AlaskaDischarge_7_mean$Discharge[6])
AlaskaDischarge_7_2013 <- data.frame(Year = 2013, Month =8 , Discharge = AlaskaDischarge_7_mean$Discharge[8])

AlaskaDischarge_7_add <- rbind(AlaskaDischarge_7_1966, AlaskaDischarge_7_2006, AlaskaDischarge_7_2007,AlaskaDischarge_7_2008, AlaskaDischarge_7_2013)

AlaskaDischarge_7.Monthly <-rbind(data.frame(AlaskaDischarge_7_ori.Monthly), data.frame(AlaskaDischarge_7_add))

#Bin 8
AlaskaDischarge_8_ori.Monthly <- AlaskaDischarge %>%
  filter(Bin == 8)%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >= 1977 & Year <= 2018)

AlaskaDischarge_8_mean <- AlaskaDischarge_8_ori.Monthly%>%
  group_by(Month)%>%
  summarise(Discharge = mean(Discharge))

AlaskaDischarge_8_1995 <- data.frame(Year = 1995, Month =10 , Discharge = AlaskaDischarge_8_mean$Discharge[10])
AlaskaDischarge_8_1999 <- data.frame(Year = 1999, Month =c(9,10,11,12) , Discharge = AlaskaDischarge_8_mean$Discharge[9:12])
AlaskaDischarge_8_2009 <- data.frame(Year = 2009, Month =c(4,5,7,8) , Discharge =c( AlaskaDischarge_8_mean$Discharge[4:5], AlaskaDischarge_8_mean$Discharge[7:8]))
AlaskaDischarge_8_2016 <- data.frame(Year = 2016, Month =c(8,10,11,12) , Discharge =c( AlaskaDischarge_8_mean$Discharge[8],AlaskaDischarge_8_mean$Discharge[10:12]))
AlaskaDischarge_8_2017 <- data.frame(Year = 2017, Month =c(1,7,8,11) , Discharge = c(AlaskaDischarge_8_mean$Discharge[1],AlaskaDischarge_8_mean$Discharge[7:8],AlaskaDischarge_8_mean$Discharge[11]))

AlaskaDischarge_8_add <- rbind(AlaskaDischarge_8_1995, AlaskaDischarge_8_1999, AlaskaDischarge_8_2009,AlaskaDischarge_8_2016, AlaskaDischarge_8_2017)

AlaskaDischarge_8.Monthly <-rbind(data.frame(AlaskaDischarge_8_ori.Monthly), data.frame(AlaskaDischarge_8_add))

#Bin 9
AlaskaDischarge_9.Monthly <- AlaskaDischarge %>%
  filter(Bin ==9)%>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  filter(Year >=1983 & Year <= 2018)
```

```{r}
# run time series
AlaskaDischarge_1_ts.Monthly <- ts(AlaskaDischarge_1.Monthly[[3]], frequency = 12)
AlaskaDischarge_2_ts.Monthly <- ts(AlaskaDischarge_2.Monthly[[3]], frequency = 12)
AlaskaDischarge_3_ts.Monthly <- ts(AlaskaDischarge_3.Monthly[[3]], frequency = 12)
AlaskaDischarge_4_ts.Monthly <- ts(AlaskaDischarge_4.Monthly[[3]], frequency = 12)
AlaskaDischarge_5_ts.Monthly <- ts(AlaskaDischarge_5.Monthly[[3]], frequency = 12)
AlaskaDischarge_6_ts.Monthly <- ts(AlaskaDischarge_6.Monthly[[3]], frequency = 12)
AlaskaDischarge_7_ts.Monthly <- ts(AlaskaDischarge_7.Monthly[[3]], frequency = 12)
AlaskaDischarge_8_ts.Monthly <- ts(AlaskaDischarge_8.Monthly[[3]], frequency = 12)
AlaskaDischarge_9_ts.Monthly <- ts(AlaskaDischarge_9.Monthly[[3]], frequency = 12)
```

```{r}
# run smk.test
#Bin 1 p = 0.1752
AlaskaDischarge_1_trend <-smk.test(AlaskaDischarge_1_ts.Monthly) 
AlaskaDischarge_1_trend

#Bin 2 p = 0.03216
AlaskaDischarge_2_trend <-smk.test(AlaskaDischarge_2_ts.Monthly) 
AlaskaDischarge_2_trend

#Bin 3 p = 0.8167
AlaskaDischarge_3_trend <-smk.test(AlaskaDischarge_3_ts.Monthly) 
AlaskaDischarge_3_trend

#Bin 4 p = 1.78e_12
AlaskaDischarge_4_trend <-smk.test(AlaskaDischarge_4_ts.Monthly) 
AlaskaDischarge_4_trend

#Bin 5 p = 2.2e-16
AlaskaDischarge_5_trend <-smk.test(AlaskaDischarge_5_ts.Monthly) 
AlaskaDischarge_5_trend

#Bin 6 p =0.0001661
AlaskaDischarge_6_trend <-smk.test(AlaskaDischarge_6_ts.Monthly) 
AlaskaDischarge_6_trend

#Bin 7 p =0.452
AlaskaDischarge_7_trend <-smk.test(AlaskaDischarge_7_ts.Monthly) 
AlaskaDischarge_7_trend

#Bin 8 p =0.6013
AlaskaDischarge_8_trend <-smk.test(AlaskaDischarge_8_ts.Monthly) 
AlaskaDischarge_8_trend

#Bin 9 p<2.2e-16
AlaskaDischarge_9_trend <-smk.test(AlaskaDischarge_9_ts.Monthly) 
AlaskaDischarge_9_trend
```

```{r}
# run sea.sens.slope
slope_1 <- sea.sens.slope(AlaskaDischarge_1_ts.Monthly)
slope_2 <- sea.sens.slope(AlaskaDischarge_2_ts.Monthly)
slope_3 <- sea.sens.slope(AlaskaDischarge_3_ts.Monthly)
slope_4 <- sea.sens.slope(AlaskaDischarge_4_ts.Monthly)
slope_5 <- sea.sens.slope(AlaskaDischarge_5_ts.Monthly)
slope_6 <- sea.sens.slope(AlaskaDischarge_6_ts.Monthly)
slope_7 <- sea.sens.slope(AlaskaDischarge_7_ts.Monthly)
slope_8 <- sea.sens.slope(AlaskaDischarge_8_ts.Monthly)
slope_9 <- sea.sens.slope(AlaskaDischarge_9_ts.Monthly)
```

```{r}
Discharge_Trend <- data.frame(Bin = c(1,2,3,4,5,6,7,8,9),Slope = c(slope_1,slope_2,slope_3,slope_4,slope_5,slope_6,slope_7,slope_8,slope_9), Trend = c(AlaskaDischarge_1_trend$p.value, AlaskaDischarge_2_trend$p.value,AlaskaDischarge_3_trend$p.value,AlaskaDischarge_4_trend$p.value,AlaskaDischarge_5_trend$p.value,AlaskaDischarge_6_trend$p.value, AlaskaDischarge_7_trend$p.value, AlaskaDischarge_8_trend$p.value, AlaskaDischarge_9_trend$p.value))

for (i in 1:9){
  if (Discharge_Trend$Trend[i] > 0.05){
    Discharge_Trend$Slope[i] <- NA
  } else {
    Discharge_Trend$Slope[i] <- Discharge_Trend$Slope[i]
  }
}

Discharge_Change <- Discharge_Trend[c(1,2)]
write.csv(Discharge_Change, "./Data/PROCESSED/Discharge_Change.csv",
          row.names = F)

```



```{r}
# add linear interplotation data for missing month for each bin
AlaskaDischarge_6 <- AlaskaDischarge %>%
  filter(Bin == 6)%>%
  drop_na()

AlaskaDischagre_6.Monthly <- AlaskaDischarge_6 %>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))%>%
  add_count(Year)
```

# bin 6
```{r}
# choose bin 6 as an example
AlaskaDischarge_6 <- AlaskaDischarge %>%
  filter(Bin == 6)%>%
  drop_na()

# dataset decomposition
AlaskaDischarge_6_ts <- ts(AlaskaDischarge_6[[6]], frequency = 365)

# Generate the decomposition
AlaskaDischarge6_Decomposed <- stl(AlaskaDischarge_6_ts, s.window = "periodic")
plot(AlaskaDischarge6_Decomposed)
```

```{r}
# extract the components 
AlaskaDischarge6_components <- as.data.frame(AlaskaDischarge6_Decomposed$time.series)
AlaskaDischarge6_components <- mutate (AlaskaDischarge6_components,Observed = AlaskaDischarge_6$Discharge, Date = AlaskaDischarge_6$DATE)

# visualize the trend map onto the data
ggplot(AlaskaDischarge6_components) +
geom_line(aes(y = Observed, x = Date), size = 0.25) + geom_line(aes(y = trend, x = Date), color = "#c13d75ff") + geom_hline(yintercept = 0, lty = 2) + ylab(expression("Discharge (ft"^3*"/s)"))+
  labs(title = "Bin 6")
```

```{r}
## 1st way to do the monthly time series
# Generate monthly values from June 1951 to October 2019
# use linear interpolation
linearinterpolation <- as.data.frame(approx(AlaskaDischarge_6$Discharge,n = 820, method = "linear"))# don't know why the data ends at 2018/09, it should be ended at 2019/10
linearinterpolation$x <- as.Date(linearinterpolation$x, origin = "1951-06-15")
names(linearinterpolation) <-c("Date", "Discharge")

# Generate time series smk.test
Discharge6_ts <- ts(linearinterpolation$Discharge, frequency = 12, start = c(1951,6,15), end = c(2018, 9, 19)) 

# Run SMK test
Discharge6_trend <- smk.test(Discharge6_ts)
Discharge6_trend
summary(Discharge6_trend)

# Bin 6 has significant seasonal variance over the period
```


```{r}
## 2nd way to do the time series
# find the monthly change of Bin 6 over time

AlaskaDischagre_6.Monthly <- AlaskaDischarge_6 %>%
  mutate(Year = year(DATE), Month = month(DATE))%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))

AlaskaDischagre_6.Monthly<-AlaskaDischagre_6.Monthly%>%
  group_by(Year, Month)%>%
  summarise(Discharge = mean(Discharge))
  
AlaskaDischagre_6_ts.Monthly <- ts(AlaskaDischagre_6.Monthly[[3]], frequency = 12)

AlaskaDischagre_6_trend.Monthly <-smk.test(AlaskaDischagre_6_ts.Monthly) 
AlaskaDischagre_6_trend.Monthly
summary(AlaskaDischagre_6_trend.Monthly)

adf.test(AlaskaDischagre_6_ts.Monthly, alternative = "stationary")
# since the p-value is 0.01 < 0.05, the data is stationary
```

```{r}
#run the arima function and search for best fit
auto.arima(AlaskaDischagre_6_ts.Monthly, trace = TRUE)
```

```{r}
# create an object that defines the best fit model
fit <- arima(AlaskaDischagre_6_ts.Monthly, c(1, 0, 0),seasonal = list(order = c(1, 1, 0), period = 12)) 

# make a prediction into the future
AlaskaDischagre_6_prediction <- predict(fit, n.ahead = 10*12)

# plot future predictions
ts.plot(AlaskaDischagre_6_ts.Monthly, AlaskaDischagre_6_prediction$pred, lty = c(1, 3))
```

2 graphs per person. Choose 6 first

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```

