---
title: "Data Wrangling"
author: "All of us"
date: "11/2/2019"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## packages
library(tidyverse)
library(dataRetrieval)
```

## Importing Data

```{r cars}
getwd() ## puts you within the main project
Alaska_Sites <- read.csv("./DATA/PROCESSED/Alaska_Streamflow_Sites.csv")
## filter for a certain latitude bin
## Bin Assignments
## Gaby = 5
## Tristen = 6 & 7
## Yixin = 1-3
## Walker = 8-11 & 4
Alaska <- filter(Alaska_Sites, Latitude_Bin == 10)
# for loop
# initialize counter
date_summary <- Alaska$site_no
size <- vector(length = 1)
counter = 1
for(site in Alaska$site_no){
  flowdata <- readNWISdv(site, "00060")
  size[counter] <- length(flowdata$Date)
  counter = counter + 1
}
sitesize <- data.frame(cbind(Alaska$site_no, size))
sitesize$V1[which.max(sitesize$size)]
```

For latitude 4, use site 15052500.
For latitude 8, use site 15453500.
For latitude 9, use site 15908000.
For latitude 10, use site 15896000.
