---
title: "Temperature Analysis"
author: "Walker Grimshaw"
date: "11/9/2019"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## install packages and read data
library(tidyverse)
library(lubridate)
library(trend)
library(forecast)
library(tseries)
library(zoo)
Alaska_Data <- read.csv("./DATA/PROCESSED/AlaskaTempPrecipDischarge.csv")
theme_set(theme_bw())
```

```{r}
## Data wrangling
## transform date column from factor to date
Alaska_Data$DATE <- as.Date(Alaska_Data$DATE, format = "%Y-%m-%d")
## Transform Bin column to factor
Alaska_Data$Bin <- as.factor(Alaska_Data$Bin)
## add rolling mean temperature column
Alaska_Data <- mutate(Alaska_Data,
                      TMAX_roll = rollmean(TMAX, 60, fill = NA))

## create plot of temperature over time for all 10 latitude bins
ggplot(Alaska_Data, aes(x = DATE, y = TMAX)) +
  geom_line(alpha = 0.8) +
  facet_wrap(~Bin, nrow = 3, ncol = 3) +
  labs(y = "Maximum Daily Temperature (F)", x = "Date")

## try with just bins 1, 5, and 9
Alaska_Data_259 <- Alaska_Data %>%
  filter(Bin %in% c(2,5,9))

ggplot(Alaska_Data, aes(x = DATE, y = TMAX, color = Bin)) +
  #geom_line() +
  geom_smooth()

## What about average monthly temperature?
Alaska_Temp_Monthly <- Alaska_Data %>%
  mutate(Year = year(DATE), Month = month(DATE)) %>%
  group_by(Year, Month, Bin) %>%
  summarize(aveTMAX = mean(TMAX, na.omit = T)) %>%
  mutate(Date = as.yearmon(paste(Year, Month), "%Y %m"))

## try plotting monthly averages, all look bad
ggplot(Alaska_Temp_Monthly, aes(x = Month, y = aveTMAX, color = Year)) +
  geom_point(alpha = 0.5) +
  scale_color_viridis_c() +
  facet_wrap(~Bin, nrow = 3, ncol = 3)

ggplot(Alaska_Temp_Monthly, aes(x = Date, y = aveTMAX)) +
  geom_line() +
  facet_wrap(~Bin, nrow = 3, ncol = 3)
```

```{r}
## decomposition of temperature series since the trends are so seasonal
## example for bin 5, must remove NAs
Alaska_Data_5 <- Alaska_Data %>%
  filter(Bin == 5 & is.na(TMAX) == FALSE)
## create time series object of temperature
Alaska_Data_5_ts <- ts(Alaska_Data_5[[9]], frequency = 365)

## decomposition
Alaska5_Decomposed <- stl(Alaska_Data_5_ts, s.window = "periodic")
plot(Alaska5_Decomposed)
```

```{r}
## Seasonal Mann-Kendall for whether temperature is changing at each site
## try creating monthly dataset for temperature
Alaska_Temp_Monthly <- Alaska_Data %>%
  mutate(Year = year(DATE), Month = month(DATE)) %>%
  group_by(Year, Month, Bin) %>%
  summarize(aveTMAX = mean(TMAX, na.rm = T)) %>%
  mutate(Date = as.yearmon(paste(Year, Month), "%Y %m"))

## Test seasonal mann kendall on bin 5 by filtering then creating ts object
Alaska_Temp_Monthly_5 <- filter(Alaska_Temp_Monthly,
                                Bin == 5)
## remove incomplete years before running sen's slope
## create count of monthly averages for each year
Alaska_Temp_Monthly_5 <- Alaska_Temp_Monthly_5 %>%
  group_by(Year) %>%
  add_count(Year) %>%
  filter(n == 12)

Alaska_Temp_Monthly_5_ts <- ts(Alaska_Temp_Monthly_5[[4]], frequency = 12)
  
## SMK Test for trend
Alaska5_Monthly_Trend <- smk.test(Alaska_Temp_Monthly_5_ts)
Alaska5_Monthly_Trend
summary(Alaska5_Monthly_Trend)

sea.sens.slope(Alaska_Temp_Monthly_5_ts)
## do I run this for each month separately?
```
There is a statistically significant change in temperature over time for bin 5. Using Sen's slope, the magnitude of this trend is 0.044, with unknown units. Maybe degrees F per year?
