---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Insert title of project here"
subtitle: "Web address for GitHub repository"
author: "Insert names of team members here"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage

<Arrow brackets are used for annotating the RMarkdown files. Text within these brackets should not appear in the final version of the PDF document>

<**General Guidelines**>
<1. Write in scientific style> 
<2. [Global options for R chunks](https://rmarkdown.rstudio.com/lesson-3.html) should be set so that only relevant output is displayed>
<3. Make sure your final knitted PDF looks professional. Format tables appropriately, size figures appropriately, make sure bulleted and numbered lists appear as such, avoid awkwardly placed page breaks, etc.>

```{r setup, include=FALSE}
## Global options to not print warning or messages
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
# Set your working directory

# Load your packages
library(tidyverse)
library(lubridate)
library(trend)
library(forecast)
library(tseries)
library(sf)
library(maps)
library(dataRetrieval)
library(viridis)
library(ggplot2)
library(scales)
library(stats)

# Set your ggplot theme
theme_set(theme_bw())

# Load your datasets

```


# Rationale and Research Questions

<Write 1-2 paragraph(s) detailing the rationale for your study. This should include both the context of the topic as well as a rationale for your choice of dataset (reason for location, variables, etc.) A few citations should be included to give context for your topic. You may choose to configure autoreferencing for your citations or add these manually.>

## Background

The climate is changing, in large part due to anthropogenic carbon emmissions. These changes have different magnitudes around the world and local impacts of climate change vary as well. Specifically, climate change is already having greater impacts near the poles than many other parts of the globe, a process known as polar amplification or arctic amplification (Serreze et al 2009). Understanding how climate change is affecting discharge, especially in Alaska, has implications for water management, ecological processes, and the larger global system (if we consider ice-albedo feedback). Many communities rely on a given amount of water from snowmelt to arrive at certain times of the year, so a shift in the quantity or timing could drastically affect downstream users and water managers. Additionally, changing the amount of flow in rivers could affect sensitive biological communities. Furthermore, changes in temperature that result in glacial or permafrost melting could reduce the amount of reflective land cover, thus disrupting larger climate systems.

<At the end of your rationale, introduce a numbered list of your questions (or an overarching question and sub-questions). Each question should be accompanied by one or more working hypotheses, inserted beneath each question.>

## Research Question

To what degree does climate change affect discharge in Alaskan streams and rivers?

This guiding question encompasses other questions we seek to answer through statistical analyses. If climate change is causing average temperatures to increase, and the magnitude of the increase is greater at higher latitudes, then higher latitude streams should demonstrate greater changes in timing and magnitude of peak flows. This study first seeks to examine if the magnitude of temperature changes increase with increasing latitude in Alaska. By analyzing historical streamflow records, we will investigate whether the magnitude of maximum daily temperature change causes a proportional change in the magnitude and timing of peak streamflow. 

Another aspect of climate change's impacts on streamflow is the potential of melting permafrost or glaciers. This analysis uses cumulative annual streamflow and cumulative annual precipitation to determine if interannual snowpack is melting with increasing average temperatures. If so, we expect the difference between annual precipitation and annual streamflow to increase over time.

\newpage

# Dataset Information

<Provide information on how the dataset for this analysis were collected, the data contained in the dataset, and any important pieces of information that are relevant to your analyses. This section should contain much of same information as the metadata file for the dataset but formatted in a way that is more narrative.>

## Discharge

Discharge data were collected from NWIS using the Data Retrieval package. The state of Alaska was divided into 10 bins of equal latitude, and daily discharge data was downloaded for the site in each latitude bin with the greatest number of samples. This dataset includes the site location, daily discharge, and county of the site, among other variables not used in the analysis.

## Temperature and Precipitation

Temperature and precipitation data were downloaded from the National Oceanic and Atmospheric Administration (NOAA) Climate Data Online web portal. As discharge stations do not collect data on temperature and precipitation, the climate data for each latitude bin were downloaded from a station in the same county as each selected discharge station. In each county, daily precipitation, maximum temperature, and minimum temperature, data were downloaded from one station. The criteria for station selection include data extending to the current date, beginning at the earliest date, with at least 80% data coverage. This dataset also includes site location.

<Describe how your team wrangled your dataset in a format similar to a methods section of a journal article.>

## Data Wrangling

<Add a table that summarizes your data structure (variables, units, ranges and/or central tendencies, data source if multiple are used, etc.). This table can be made in markdown text or inserted as a `kable` function in an R chunk. If the latter, do not include the code used to generate your table.>

| Variable | Units (if known) | Type of Variable | Hypothesis | 
|------:|:-----|---------|:------:|
| Discharge | Cubic feet per second | Response | 1a, 1b, 1c |
| Site Number | Latitude/Longitude | Predictor | 1a |
| Date Time | Year/Month/Day | Predictor | 1c |
| Date of First Snowmelt | Year/Month/Day | Predictor | 1a, 1b, 1c |
| Air Temperature | Celsius | Predictor | 1b |
| Precipitation | Millimeters | Predictor | 1a, 1c |
| HUC 8 Watershed Size | Square Meters | Predictor | 1a, 1b | 
| Permafrost Melt | Qualitative | Predictor | 1b | 
| Glacial Coverage/Melting | Qualitative | Predictor | 1b |

\newpage

# Exploratory Analysis 

<Insert exploratory visualizations of your dataset. This may include, but is not limited to, graphs illustrating the distributions of variables of interest and/or maps of the spatial context of your dataset. Format your R chunks so that graphs are displayed but code is not displayed. Accompany these graphs with text sections that describe the visualizations and provide context for further analyses.>

<Each figure should be accompanied by a caption, and each figure should be referenced within the text>

\newpage

# Analysis

<Insert visualizations and text describing your main analyses. Format your R chunks so that graphs are displayed but code and other output is not displayed. Instead, describe the results of any statistical tests in the main text (e.g., "Variable x was significantly different among y groups (ANOVA; df = 300, F = 5.55, p < 0.0001)"). Each paragraph, accompanied by one or more visualizations, should describe the major findings and how they relate to the question and hypotheses. Divide this section into subsections, one for each research question.>

<Each figure should be accompanied by a caption, and each figure should be referenced within the text>

## Question 1: <insert specific question here and add additional subsections for additional questions below>

## Question 2: 


The Climate Science Special Report estimates that maximum temperature increases in Alaska since between the first half of the 20th century and the past 30 years have been 1.43 degrees F (https://science2017.globalchange.gov/chapter/6/).

\newpage

# Summary and Conclusions
<Summarize your major findings from your analyses in a few paragraphs. What conclusions do you draw from your findings? Relate your findings back to the original research questions and rationale.>

\newpage

# References
<add references here> 
Serreze, M. C., Barrett, A. P., Stroeve, J. C., Kindig, D. N., and Holland, M. M.: The emergence of surface-based Arctic amplification, The Cryosphere, 3, 11–19, https://doi.org/10.5194/tc-3-11-2009, 2009.
